#include <catch2/catch_template_test_macros.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cstdint>
#include <random>

#include "ulvt/finite_fields/ghash_ctmul32.cuh"
#include "ulvt/finite_fields/ghash_ctmul64.cuh"

namespace {

// C++ has no 128-bit integer literals, so build one from two 64-bit halves.
constexpr __uint128_t u128(uint64_t hi, uint64_t lo) { return ((__uint128_t)hi << 64) | lo; }

// ---------------------------------------------------------------------------
// Known-answer vectors: c == a * b in GF(2^128), generated by the reference
// Binius implementation. These pin the bit/limb convention authoritatively.
// ---------------------------------------------------------------------------

struct MulTestExample {
	__uint128_t a, b, c;
};

const MulTestExample kVectors[] = {
	{u128(0x31fa7e9dd7096a70, 0xe649049402909f71), u128(0x135717bed0bf8766, 0x86408372fb9bfa3e),
	 u128(0x0c1dee0c319052eb, 0x28ab6f2e1a7ae3a5)},
	{u128(0xbbc0196ec2f2d27a, 0x3bfb1f0878a58bc4), u128(0xf6b86e916df97d39, 0xf52619552644dc6b),
	 u128(0xd2d2bdda17e01ef2, 0xea241168b4d423bc)},
	{u128(0xd129240fdcf2ae27, 0x90fb5da0a2fb8ac1), u128(0xf541227f84e0a3cc, 0xfa559c9860722198),
	 u128(0x2fe60c7b82a4732b, 0xd6072a57a4002043)},
	{u128(0x1afbbd6c50f3455e, 0x9705103efbb9839e), u128(0x1dcb2dc495f26af4, 0xd56c7f1504663cf6),
	 u128(0xfe4434b442d4da48, 0x5ed0930d2ca9cd15)},
	{u128(0x2f0a405454399a07, 0xe47497b10734c637), u128(0x9a93c66834e4701f, 0x93137025486ccf19),
	 u128(0xf31ca0e9d8dffc1b, 0xb4f130d512ceb7ef)},
	{u128(0xf56534f1d4fd1007, 0x140f6ab52e16e8c6), u128(0x3170567beefe57a1, 0x001d21a889f58053),
	 u128(0x5b6817a75d5c82f4, 0x24109a04aa985a4e)},
	{u128(0x04939d284cca0029, 0xb367829312c638c6), u128(0x04c773c56adf1847, 0x776435e3ebd4eed4),
	 u128(0x2f261413347d5373, 0x0b5160520ca1bf07)},
	{u128(0xb5de4cd951985bec, 0x053b31ce35db46bf), u128(0x89b5d7bcbd84975d, 0x53dc258fa5ea18a9),
	 u128(0x14f396b5ab8655c0, 0xf94734ff0d1eb9bf)},
	{u128(0x2d5480b78bc34a90, 0xa8dfa2aad7850972), u128(0xddd86f4495a41072, 0xfe6e375d3d6a4d22),
	 u128(0x087b83221c6538f7, 0x03c95c565e9a6749)},
	{u128(0xa30d76c9d2866d73, 0x7564a78b2e4f28e4), u128(0x61c0025ccd11d314, 0x1f4e9e3b0bb0aab6),
	 u128(0x1a19974d338363f6, 0x858825d80a114741)},
	{u128(0xcbe3f56947c43328, 0x939fcdfdb38aa83c), u128(0x61197967ee61d120, 0x110808dbfb32f285),
	 u128(0xf65f17080268ee97, 0xe7938199925a09c2)},
	{u128(0x0ba194c44a80c73f, 0xf2584006007e93a7), u128(0x8ecaac51d88aea4b, 0x32a8eb9d86b8717f),
	 u128(0x894ec0b3543e3d9a, 0x8b69466f767573ed)},
	{u128(0x438925556a5d5ab6, 0x5ced83d884953b04), u128(0x5c64c3be990c6377, 0x0096a342933c64be),
	 u128(0x2fef3d9bfacaa918, 0xab32971a4b8d4bdd)},
	{u128(0x47e3c02576d03ffc, 0x9413e64321dc0c20), u128(0xa4e4f2b35b3adb0c, 0x381760176ed0ff93),
	 u128(0xc19e547fb37d2d7c, 0x94159a7a62bf56e7)},
	{u128(0x876015c9d0feced9, 0x66373da4a145bb33), u128(0xba6e32826607349f, 0x4d9dfe8ce93889f9),
	 u128(0xe240fe29ae2499e0, 0x44a4f9e5078b321e)},
	{u128(0x9a4693a14f751f71, 0x2451c6f9b72d03c9), u128(0x4445d184eea1986e, 0x7829cd6b268fde84),
	 u128(0xc57130ffa243b2ae, 0x3b674ee27d38ea7a)},
	{u128(0xcf63b270d475730d, 0xcca2110951bd70ca), u128(0xe15d5889775389d7, 0x506cbbb9e243e34a),
	 u128(0x7ea1d097aa57b9be, 0x90539fdb04ae9172)},
	{u128(0x26914f0309c493e9, 0x3cf0a4e47e3bcc23), u128(0x339de0d72ee8463f, 0x9f2b688ea1121268),
	 u128(0x19ff0c21d6355532, 0xc6a0f749b6a49984)},
	{u128(0x55b382cfa17535bf, 0x02eab9c949526539), u128(0xce3c540725c77d50, 0x99ba5c8702eee4d0),
	 u128(0xb73a87e0414ede88, 0x8c2db8fde736e7ce)},
	{u128(0xacf0c3bad85f000d, 0x2516230cb84d551b), u128(0xbab8a48a5c6a7292, 0x5ae32a52c7f77444),
	 u128(0x90aac8472501479c, 0x4fd886287fd29b89)},
	{u128(0x5559719e8f2c547f, 0x81847558241c6dd1), u128(0x8d76328d900bc22e, 0xdb9f2f816a801499),
	 u128(0x8fec52709922b759, 0x996e9b4d9acac9ba)},
	{u128(0x526c3b18f026b7b1, 0x5ba121ef41e2c989), u128(0xb859a9f8faf1aaf3, 0x7f0dd1b0eca5cdef),
	 u128(0x7334b4cc9d711491, 0x89b68a4c9a42a377)},
	{u128(0x3cf4f1548047cac8, 0xb8a47245d7ed94f7), u128(0xa3122704ec328542, 0x8c65933148c31e7b),
	 u128(0xb6316e230d16cf16, 0x6b88c9e24c3d663f)},
	{u128(0x3b95550a856c673a, 0xe7d9b2485ad99322), u128(0x5a4fc3848c556d36, 0x4c967d6c2b77541c),
	 u128(0x7af2a93d607c13aa, 0xf6f722a536425569)},
	{u128(0xdd45adff4e81daf2, 0x6f6e21a67bdfe17b), u128(0x9eb862b7ba4e8055, 0x80b816daba1e2ead),
	 u128(0xb5af3cd0520182d2, 0x75ccf4b5c6509d5f)},
	{u128(0x3fc3a07397ebc685, 0x5a2a8d9097a21545), u128(0x86e09b853c23fec9, 0xf39e4c1ef7cd5bd7),
	 u128(0x6e7dabeaa4d6b54f, 0xf5a709623c0c8e48)},
	{u128(0x35f7177357bed973, 0x6b285f5a9f04384a), u128(0xd788d3f51ed73668, 0x44647ce4771cffd6),
	 u128(0x3f6f497c768122f7, 0x2dfa362a61a95775)},
};

// ---------------------------------------------------------------------------
// Independent reference implementation of GF(2^128) multiplication.
//
// Elements are polynomials over GF(2) with bit i representing the coefficient
// of X^i (little-endian), reduced modulo X^128 + X^7 + X^2 + X + 1. This is a
// deliberately naive, obviously-correct schoolbook implementation used to
// cross-check the optimized BearSSL-derived kernels over many inputs.
// ---------------------------------------------------------------------------

// 256-bit value, little-endian limbs.
struct U256 {
	uint64_t w[4];
};

// Carryless (XOR) product of two 128-bit polynomials into a 256-bit result.
U256 clmul_ref(__uint128_t a, __uint128_t b) {
	U256 p{{0, 0, 0, 0}};
	auto flip = [&](int bit) { p.w[bit >> 6] ^= (uint64_t)1 << (bit & 63); };
	for (int i = 0; i < 128; ++i) {
		if (((a >> i) & 1) == 0) {
			continue;
		}
		for (int j = 0; j < 128; ++j) {
			if ((b >> j) & 1) {
				flip(i + j);
			}
		}
	}
	return p;
}

// Reduce a 256-bit value modulo X^128 + X^7 + X^2 + X + 1, i.e. X^128 == 0x87.
__uint128_t reduce_ref(U256 p) {
	auto get = [&](int bit) { return (p.w[bit >> 6] >> (bit & 63)) & 1; };
	auto flip = [&](int bit) { p.w[bit >> 6] ^= (uint64_t)1 << (bit & 63); };
	// Process from the top down so each fold only ever creates lower-order
	// bits, which are reduced later in the same loop.
	for (int bit = 255; bit >= 128; --bit) {
		if (!get(bit)) {
			continue;
		}
		flip(bit);                   // clear the high term
		const int base = bit - 128;  // X^bit == X^base * (X^7 + X^2 + X + 1)
		flip(base + 0);
		flip(base + 1);
		flip(base + 2);
		flip(base + 7);
	}
	return ((__uint128_t)p.w[1] << 64) | p.w[0];
}

__uint128_t mul_ref(__uint128_t a, __uint128_t b) { return reduce_ref(clmul_ref(a, b)); }

// Conversions from the two Ghash representations back to __uint128_t.
__uint128_t to_u128(const ghash_ctmul64::Ghash& g) {
	return ((__uint128_t)g.limbs[1] << 64) | g.limbs[0];
}

__uint128_t to_u128(const ghash_ctmul32::Ghash& g) {
	return ((__uint128_t)g.limbs[3] << 96) | ((__uint128_t)g.limbs[2] << 64) |
		   ((__uint128_t)g.limbs[1] << 32) | g.limbs[0];
}

}  // namespace

// The independent reference must agree with the project's known-answer vectors;
// if this fails, the reference's convention is wrong (not the kernels).
TEST_CASE("reference matches known-answer vectors", "[ghash][mul][kat]") {
	for (const auto& v : kVectors) {
		REQUIRE(mul_ref(v.a, v.b) == v.c);
	}
}

TEMPLATE_TEST_CASE(
	"Ghash known-answer vectors", "[ghash][mul][kat]", ghash_ctmul32::Ghash, ghash_ctmul64::Ghash
) {
	using Ghash = TestType;
	for (const auto& v : kVectors) {
		const Ghash product = Ghash(v.a) * Ghash(v.b);
		REQUIRE(to_u128(product) == v.c);
	}
}

// ---------------------------------------------------------------------------
// Small structured cases that pin the representation, reduction polynomial, and
// high-bit recovery one property at a time.
// ---------------------------------------------------------------------------

TEMPLATE_TEST_CASE(
	"Ghash multiplication structured cases", "[ghash][mul]", ghash_ctmul32::Ghash,
	ghash_ctmul64::Ghash
) {
	using Ghash = TestType;

	const __uint128_t one = 1;
	const __uint128_t X = (__uint128_t)1 << 1;       // the polynomial X
	const __uint128_t X127 = (__uint128_t)1 << 127;  // X^127

	SECTION("multiplicative identity") {
		const __uint128_t a = u128(0xdeadbeefcafef00d, 0x0123456789abcdef);
		REQUIRE((Ghash(a) * Ghash(one)) == Ghash(a));
		REQUIRE((Ghash(one) * Ghash(a)) == Ghash(a));
	}

	SECTION("multiplication by zero") {
		const __uint128_t a = u128(0xfeedfacefeedface, 0x1122334455667788);
		REQUIRE((Ghash(a) * Ghash((__uint128_t)0)) == Ghash((__uint128_t)0));
	}

	SECTION("X * X == X^2") { REQUIRE((Ghash(X) * Ghash(X)) == Ghash((__uint128_t)1 << 2)); }

	// X^127 * X == X^128 == X^7 + X^2 + X + 1 == 0x87. Pins the reduction.
	SECTION("X^127 * X folds to the modulus tail") {
		REQUIRE((Ghash(X127) * Ghash(X)) == Ghash((__uint128_t)0x87));
	}
}

// ---------------------------------------------------------------------------
// Algebraic structure over random inputs.
// ---------------------------------------------------------------------------

TEMPLATE_TEST_CASE(
	"Ghash field axioms", "[ghash][mul]", ghash_ctmul32::Ghash, ghash_ctmul64::Ghash
) {
	using Ghash = TestType;

	std::mt19937_64 rng(0xC0FFEEull);
	auto rand128 = [&]() { return u128(rng(), rng()); };

	for (int trial = 0; trial < 256; ++trial) {
		const __uint128_t a = rand128();
		const __uint128_t b = rand128();
		const __uint128_t c = rand128();
		const Ghash ga(a), gb(b), gc(c);

		// Addition and subtraction are XOR.
		REQUIRE((ga + gb) == Ghash(a ^ b));
		REQUIRE((ga - gb) == Ghash(a ^ b));
		REQUIRE((ga + ga) == Ghash((__uint128_t)0));

		// Commutativity, associativity, distributivity.
		REQUIRE((ga * gb) == (gb * ga));
		REQUIRE(((ga * gb) * gc) == (ga * (gb * gc)));
		REQUIRE((ga * (gb + gc)) == ((ga * gb) + (ga * gc)));
	}
}

// ---------------------------------------------------------------------------
// Each kernel agrees with the independent reference over many random inputs,
// including clmad's full 256-bit carryless product before reduction.
// ---------------------------------------------------------------------------

TEST_CASE("ghash_ctmul64 matches reference", "[ghash][mul]") {
	std::mt19937_64 rng(1);
	auto rand128 = [&]() { return u128(rng(), rng()); };

	for (int trial = 0; trial < 4096; ++trial) {
		const __uint128_t a = rand128();
		const __uint128_t b = rand128();

		ghash_ctmul64::GhashWide wide;
		ghash_ctmul64::clmad(ghash_ctmul64::Ghash(a), ghash_ctmul64::Ghash(b), wide);
		const U256 expected_wide = clmul_ref(a, b);
		REQUIRE(wide.limbs[0] == expected_wide.w[0]);
		REQUIRE(wide.limbs[1] == expected_wide.w[1]);
		REQUIRE(wide.limbs[2] == expected_wide.w[2]);
		REQUIRE(wide.limbs[3] == expected_wide.w[3]);

		const ghash_ctmul64::Ghash product = ghash_ctmul64::Ghash(a) * ghash_ctmul64::Ghash(b);
		REQUIRE(to_u128(product) == mul_ref(a, b));
	}
}

TEST_CASE("ghash_ctmul32 matches reference", "[ghash][mul]") {
	std::mt19937_64 rng(2);
	auto rand128 = [&]() { return u128(rng(), rng()); };

	for (int trial = 0; trial < 4096; ++trial) {
		const __uint128_t a = rand128();
		const __uint128_t b = rand128();

		ghash_ctmul32::GhashWide wide;
		ghash_ctmul32::clmad(ghash_ctmul32::Ghash(a), ghash_ctmul32::Ghash(b), wide);
		const U256 expected_wide = clmul_ref(a, b);
		for (int k = 0; k < 8; ++k) {
			const uint32_t expected = (uint32_t)(expected_wide.w[k / 2] >> (32 * (k % 2)));
			REQUIRE(wide.limbs[k] == expected);
		}

		const ghash_ctmul32::Ghash product = ghash_ctmul32::Ghash(a) * ghash_ctmul32::Ghash(b);
		REQUIRE(to_u128(product) == mul_ref(a, b));
	}
}

// The two independent kernels must agree with each other.
TEST_CASE("ghash_ctmul32 and ghash_ctmul64 agree", "[ghash][mul]") {
	std::mt19937_64 rng(3);
	auto rand128 = [&]() { return u128(rng(), rng()); };

	for (int trial = 0; trial < 4096; ++trial) {
		const __uint128_t a = rand128();
		const __uint128_t b = rand128();

		const __uint128_t p32 = to_u128(ghash_ctmul32::Ghash(a) * ghash_ctmul32::Ghash(b));
		const __uint128_t p64 = to_u128(ghash_ctmul64::Ghash(a) * ghash_ctmul64::Ghash(b));
		REQUIRE(p32 == p64);
	}
}
